### ISSUE TITLE
Robot spins around and then shoots a ball in a random direction

### ISSUE THREAD

**Issue by ninjas28** [EastsidePreparatorySchool/EPSilonRed#1]
This is caused by driver error, the program locks up during the autofire sequence. If any joystick is not in its zero position this will cause whatever movement commands to be sustained throughout the entire firing sequence. Most commonly this happens when the autofire sequence is initialized while the driver is finalizing the shot angle. 

A solution is to make the autofire its own thread, but that carries with it some complications. If it was a separate thread, you would theoretically be able to send driver commands to the crossbow motors while the autofire sequence is running, jamming up the crossbow and potentially causing a misfire. Not sure how to lock out the driver controls while the autonomous firing is taking place, need some sort of flag.

**Comment by gunnarmein** [comment]
java.util.concurrent.Semaphore will do the trick.

**Comment by gunnarmein** [comment]
I occurs to me that your routine could have two parts - 
a) pulling back, lock down, letting out
b) firing

a) does belong on its own thread.

**Comment by ninjas28** [comment]
Fixed in 51278fe197575a486a0415456c83eb7cbc261bc8.
